### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by defuse**
**WARNING: Rebasing**

### CODE REVIEW

**Comment by defuse** [comment]
WARNING: I'm about to rebase `v2.0` onto master.

**Comment by defuse** [comment]
Actually I'm not going to rebase because the v2.0 branch has a crap ton of merges on it and I'd have to redo all the conflict resolutions.

**Comment by defuse** [comment]
Just going to merge it into master manually.

**Comment by paragonie-scott** [comment]
:+1:

**Comment by defuse** [comment]
Ah fuck, I forgot to pull master before I merged. Time to `rm -rf` the repository and clone it again!

**Pull request merged**
