### PR TITLE
Use more environment friendly exception handling

### PR DESCRIPTION
**Pull request by mattsah**
This causes the handler to be registered with each function and then restored
when an exception is thrown or in the case that the method returns proper.

### CODE REVIEW

**Comment by mattsah** [comment]
@defuse 

This is split and also fixes the problem you brought up on the previous one.  I closed the other request.

This one should enable restoring the exception handler in either case, and doesn't have all the doc cleanup.  Please let me know if you still want the docs and cleanup.

**Comment by mattsah** [comment]
Please hold on this.  Additional testing has shown it *does not always work*.  Looking for something more reliable.

**Comment by mattsah** [comment]
Closing this... after multiple additional attempts... this just doesn't seem viable.

**Comment by defuse** [comment]
Thanks very much for trying!

**Pull request closed without merging**
