### PR TITLE
Use openssl_ for CSPRNG

### PR DESCRIPTION
**Pull request by sarciszewski**
Make `mcrypt_create_iv()` optional.

### CODE REVIEW

**Comment by defuse** [comment]
Note to self: We can remove the mcrypt dependency in composer after this.

**Comment by defuse** [comment]
Should we keep the `mcrypt_create_iv` at all? If they don't have OpenSSL, the encryption won't work, right, or is there a circumstance where encryption will work but the openssl RNG isn't available?

**Comment by sarciszewski** [comment]
Since we need 5.4.x now, we can get by with just openssl. And if openssl's PRNG isn't secure, TLS is doomed.

**Comment by defuse** [comment]
Okay, let's get rid of the `mcrypt_create_iv()`

**Comment by sarciszewski** [comment]
This should be ready to merge, then.

**Pull request merged**
