### PR TITLE
Made exception handler isolated on crypto functions only + cleanup

### PR DESCRIPTION
**Pull request by mattsah**
Cleanup was done in order to provide clearer API documentation for
other users which appeared to be lacking.  Documentation was
generated using sage (https://github.com/dotink/sage), hence the
addition of the sage.config

### CODE REVIEW

**Comment by mattsah** [comment]
This solves half of the issues in #41, the other half is in https://github.com/defuse/php-encryption/pull/31 although would need to be modified to load src/Crypto.php not just Crypto.php.

If both of these are pulled in, and you register the package on packagist, I think you'd see a lot more people using this which could only be a good thing all around.

**Comment by defuse** [comment]
Thanks, I'll review this as soon as I have time.

Would it be easy to make separate pull requests for the documentation and exception handling (or at least have them in separate commits)? It would be nice to have security-critical changes isolated. If not (like, if it's not something that would take 2 minutes), don't worry about it.

**Comment by mattsah** [comment]
I don't know if I can modify this pull request per se.  I could split them into two separate commit though (which may or may not modify this original pull request).

**Comment by mattsah** [comment]
I'm closing this and moving to the split which also has a fix for the aforementioned issue.

**Pull request closed without merging**
