### PR TITLE
Add helper method for openssl_cipher_iv_length().

### PR DESCRIPTION
**Pull request by twistor**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
> 1) Defuse\Crypto\FileTest::testFileCreateRandomKey
> 
> Failed asserting that Binary String: 0xec5a666a1d861...c6fcc64 is an instance of class "\Defuse\Crypto\Key".

I'm not sure where this change-set caused the reported failure (was it at the same time as another change?). This is a good idea, however.

**Comment by twistor** [comment]
That's not from this patch.

I get the same failure running v2.0 locally.

**Comment by paragonie-scott** [comment]
Okay, well this looks great to me. :+1:

**Comment by defuse** [comment]
@paragonie-scott Yeah, that was a bug. I think it's fixed in the v2.0 branch now.

**Pull request merged**
