### PR TITLE
Harden the autoloader against unserialize -> LFI risks.

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by defuse** [comment]
How about we just map class names to paths?

```php
$map = array(
  'Crypto' => 'src/Crypto.php',
  'Core' => 'src/Core.php',
 ...
)

**Comment by paragonie-scott** [comment]
Yeah, that's probably more sensible. Does #116 cover this already? (If so, I will close. If not, I will fix.)

**Comment by defuse** [comment]
#116 doesn't do it yet, feel free to do it if you want.

**Comment by paragonie-scott** [comment]
Okay, I believe this is ready to go. :)

**Comment by defuse** [comment]
Thanks. Going to attempt rebasing this onto my other WIP branch :-)

**Comment by defuse** [comment]
Can't figure that out right now, I'll do it tomorrow. :-)

**Comment by defuse** [comment]
(If you happen to get to it first, I added some new files, and I intend to change it to do `$classmap[$relative_class]` for efficiency).

**Comment by paragonie-scott** [comment]
Dammit, I did *not* mean to push that commit.

**Pull request closed without merging**
