### PR TITLE
modified condition to avoid an inspection error in PHPStorm

### PR DESCRIPTION
**Pull request by karlpatrickespiritu**
screenshot from 2015-09-28 23 47 37

### CODE REVIEW

**Comment by paragonie-scott** [comment]
This reminds me of leaving a bunch of `if (false) { $object = new Explicit\Object\Path\Name; }` in my PHP scripts to make Netbeans ctrl+click through to the desired method.

That said, :+1: we don't need to worry about `\Throwable` or `\Error`, because even when PHP 7 is out, all of the exceptions here extend `\Exception`.

**Comment by sethbattin** [comment]
There's an alternate way to make phpstorm recognize the object, without a code change.  Just add an annotation comment to the private variable:

`/* @var \Exception */
private $rethrow */

If code changes are undesirable, then make the code inspector leverage it's additional advantage.

**Comment by paragonie-scott** [comment]
> If code changes are undesirable, then make the code inspector leverage it's additional advantage.

That's a good point too. Given these two solutions, the annotation should accomplish the same result with less runtime overhead. (Note to self: Take advantage of annotations.)

**Comment by karlpatrickespiritu** [comment]
the @var \Exception works like a charm. didn't know about that. thanks.

**Comment by karlpatrickespiritu** [comment]
didn't know about the /* @var \Exception */ just now. thanks for the info. and good point, less runtime overhead :+1:

**Comment by sstok** [comment]
:+1:

**Comment by defuse** [comment]
We're going to get rid of that exception handler override thing (#97), so I'm closing this.

**Pull request closed without merging**
