### PR TITLE
Add changePassword method, addressing #371

### PR DESCRIPTION
**Pull request by artfulrobot**

### CODE REVIEW

**Comment by defuse** [comment]
Some possible usability pitfalls here are:

- Someone thinks just calling changePassword is enough, and doesn't actually save the key again with the new password (seems likely with this API).
- Someone calls changePassword and saves the new key but leaves old ones lying around, so the old password is still effectively usable.
- anything else?

What do we think about this API in terms of usability? I can imagine another way to do it, which would be to have `changePassword` return a new instance of `KeyProtectedByPassword` and disable or leave the old instance alone. Maybe that would help with the first point, but I'm not sure.

**Comment by paragonie-security** [comment]
Add a `__destruct()` method that throws an exception if `save()` was never invoked.

**Comment by defuse** [comment]
I think I'll bring this in as-is, with documentation and adding a test to make sure the old password doesn't still decrypt the old key. I don't think there is an API design that could prevent people from not deleting old encrypted keys, and if someone forgets to save the new key, then they probably won't have overwritten the old encrypted key, so they won't lose any data (unless they delete/forget the old password).

**Comment by defuse** [comment]
I pulled this into #393.

**Pull request closed without merging**
