### PR TITLE
Add more instructions to the README

### PR DESCRIPTION
**Pull request by paragonie-scott**
(Not finished yet.)

### CODE REVIEW

**Comment by paragonie-scott** [comment]
This probably needs a little bit more improvement, but I think it covers the major features.

**Comment by defuse** [comment]
Ugh, yet another PR that's broken because of github.

**Comment by defuse** [comment]
Any chance you could resubmit this PR rebased on top of v2.0? Mainly I just want the github bug to go away so I can actually see what's changed lol

**Comment by paragonie-scott** [comment]
Yeah, no problem.

**Pull request closed without merging**
