### PR TITLE
Create LICENSE file

### PR DESCRIPTION
**Pull request by paragonie-scott**
Makes it clearer to people what the terms of its release are, even though this is in composer.json

### CODE REVIEW

**Comment by PeeHaa** [comment]
Sorry to hijack this PR, but is there a specific reason the "All rights reserved" line is included?

**Comment by adamcaudill** [comment]
@PeeHaa That's a standard part of the BSD license.

**Comment by PeeHaa** [comment]
Thanks for clarifying. The reason I didn't expect that line is because I was under the assumption that the library was [MIT licensed instead](https://github.com/defuse/php-encryption/blob/master/composer.json#L4).

Could you please fix the composer.json file or do you want me to open a separate issue for it?

Either way here is a token of my appreciation in the form of a [friday link](https://www.youtube.com/watch?v=kfVsfOSbJY0) for your excellent work on this library.

**Comment by paragonie-scott** [comment]
I'm going to close this PR because I'm not confident that my change is correct.

@defuse If you can create a LICENSE file (and update the composer.json, if necessary), that would probably clarify the licensing for everyone. :)

**Pull request closed without merging**
